# Generated by Django 2.0.7 on 2018-07-03 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baemin', '0003_remove_shop_name_kr'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='name_kr',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='name_location',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
