# Generated by Django 2.0.7 on 2018-07-03 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baemin', '0004_auto_20180703_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
